// web-ui/src/pages/Login.tsx
import { useState } from 'react'
import { Link, useNavigate, useLocation } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import toast from 'react-hot-toast'
import { EyeIcon, EyeSlashIcon } from '@heroicons/react/24/outline'

import { useAuthStore } from '@/stores/authStore'
import { LoginForm } from '@/types'
import { Spinner } from '@/components/ui/Spinner'

export function Login() {
  const [showPassword, setShowPassword] = useState(false)
  const navigate = useNavigate()
  const location = useLocation()
  const { login, isLoading } = useAuthStore()

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<LoginForm>()

  const onSubmit = async (data: LoginForm) => {
    try {
      await login(data.email, data.password)
      
      // Redirect to intended page or dashboard
      const from = location.state?.from?.pathname || '/dashboard'
      navigate(from, { replace: true })
      
      toast.success('Welcome back!')
    } catch (error) {
      // Error is already handled in the store
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-secondary-50 dark:bg-secondary-900 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <div>
          <div className="mx-auto h-12 w-12 bg-primary-600 rounded-lg flex items-center justify-center">
            <span className="text-white font-bold text-xl">D</span>
          </div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-secondary-900 dark:text-white">
            Sign in to DataMesh
          </h2>
          <p className="mt-2 text-center text-sm text-secondary-600 dark:text-secondary-400">
            Or{' '}
            <Link
              to="/register"
              className="font-medium text-primary-600 hover:text-primary-500"
            >
              create a new account
            </Link>
          </p>
        </div>
        
        <form className="mt-8 space-y-6" onSubmit={handleSubmit(onSubmit)}>
          <div className="space-y-4">
            <div>
              <label htmlFor="email" className="label">
                Email address
              </label>
              <input
                {...register('email', {
                  required: 'Email is required',
                  pattern: {
                    value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                    message: 'Invalid email address',
                  },
                })}
                type="email"
                autoComplete="email"
                className="input"
                placeholder="Enter your email"
              />
              {errors.email && (
                <p className="mt-1 text-sm text-danger-600">{errors.email.message}</p>
              )}
            </div>
            
            <div>
              <label htmlFor="password" className="label">
                Password
              </label>
              <div className="relative">
                <input
                  {...register('password', {
                    required: 'Password is required',
                    minLength: {
                      value: 6,
                      message: 'Password must be at least 6 characters',
                    },
                  })}
                  type={showPassword ? 'text' : 'password'}
                  autoComplete="current-password"
                  className="input pr-10"
                  placeholder="Enter your password"
                />
                <button
                  type="button"
                  className="absolute inset-y-0 right-0 pr-3 flex items-center"
                  onClick={() => setShowPassword(!showPassword)}
                >
                  {showPassword ? (
                    <EyeSlashIcon className="h-5 w-5 text-secondary-400" />
                  ) : (
                    <EyeIcon className="h-5 w-5 text-secondary-400" />
                  )}
                </button>
              </div>
              {errors.password && (
                <p className="mt-1 text-sm text-danger-600">{errors.password.message}</p>
              )}
            </div>
          </div>

          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <input
                id="remember-me"
                name="remember-me"
                type="checkbox"
                className="h-4 w-4 text-primary-600 focus:ring-primary-500 border-secondary-300 rounded"
              />
              <label htmlFor="remember-me" className="ml-2 block text-sm text-secondary-900 dark:text-secondary-300">
                Remember me
              </label>
            </div>

            <div className="text-sm">
              <a
                href="#"
                className="font-medium text-primary-600 hover:text-primary-500"
              >
                Forgot your password?
              </a>
            </div>
          </div>

          <div>
            <button
              type="submit"
              disabled={isLoading}
              className="btn-primary w-full flex justify-center py-3"
            >
              {isLoading ? (
                <>
                  <Spinner size="sm" className="mr-2" />
                  Signing in...
                </>
              ) : (
                'Sign in'
              )}
            </button>
          </div>

          <div className="mt-6">
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-secondary-300 dark:border-secondary-600" />
              </div>
              <div className="relative flex justify-center text-sm">
                <span className="px-2 bg-secondary-50 dark:bg-secondary-900 text-secondary-500">
                  New to DataMesh?
                </span>
              </div>
            </div>

            <div className="mt-6">
              <Link
                to="/register"
                className="w-full flex justify-center py-3 px-4 border border-secondary-300 dark:border-secondary-600 rounded-md shadow-sm text-sm font-medium text-secondary-700 dark:text-secondary-300 bg-white dark:bg-secondary-800 hover:bg-secondary-50 dark:hover:bg-secondary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
              >
                Create new account
              </Link>
            </div>
          </div>
        </form>
      </div>
    </div>
  )
}

// web-interface/src/views/auth/Login.vue
<template>
  <div class="login-form">
    <h2>Sign In</h2>
    <p>Access your DataMesh account</p>
    
    <el-form
      ref="loginFormRef"
      :model="loginForm"
      :rules="loginRules"
      @submit.prevent="handleLogin"
    >
      <el-form-item prop="email">
        <el-input
          v-model="loginForm.email"
          type="email"
          placeholder="Email address"
          size="large"
          :prefix-icon="Message"
          :disabled="loading"
        />
      </el-form-item>
      
      <el-form-item prop="password">
        <el-input
          v-model="loginForm.password"
          type="password"
          placeholder="Password"
          size="large"
          :prefix-icon="Lock"
          :disabled="loading"
          show-password
          @keyup.enter="handleLogin"
        />
      </el-form-item>
      
      <el-form-item>
        <div class="login-options">
          <el-checkbox
            v-model="loginForm.remember"
            :disabled="loading"
          >
            Remember me
          </el-checkbox>
          <router-link
            to="/auth/forgot-password"
            class="forgot-link"
          >
            Forgot password?
          </router-link>
        </div>
      </el-form-item>
      
      <el-form-item>
        <el-button
          type="primary"
          size="large"
          :loading="loading"
          class="login-button"
          @click="handleLogin"
        >
          Sign In
        </el-button>
      </el-form-item>
    </el-form>
    
    <div class="login-footer">
      <p>
        Don't have an account? <router-link to="/auth/register">
          Sign up
        </router-link>
      </p>
    </div>
    
    <!-- Demo credentials -->
    <div
      v-if="isDev"
      class="demo-credentials"
    >
      <el-divider>Demo Credentials</el-divider>
      <div class="demo-buttons">
        <el-button
          size="small"
          @click="setDemoCredentials('admin')"
        >
          Admin Demo
        </el-button>
        <el-button
          size="small"
          @click="setDemoCredentials('user')"
        >
          User Demo
        </el-button>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, reactive, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../../store/auth'
import { ElMessage } from 'element-plus'
import { Message, Lock } from '@element-plus/icons-vue'

export default {
  name: 'Login',
  setup() {
    const router = useRouter()
    const authStore = useAuthStore()
    
    const loginFormRef = ref()
    const loading = ref(false)
    const isDev = computed(() => import.meta.env.DEV)
    
    const loginForm = reactive({
      email: '',
      password: '',
      remember: false
    })
    
    const loginRules = {
      email: [
        { required: true, message: 'Please enter your email address', trigger: 'blur' },
        { type: 'email', message: 'Please enter a valid email address', trigger: 'blur' }
      ],
      password: [
        { required: true, message: 'Please enter your password', trigger: 'blur' },
        { min: 6, message: 'Password must be at least 6 characters', trigger: 'blur' }
      ]
    }
    
    const handleLogin = async () => {
      if (!loginFormRef.value) return
      
      try {
        await loginFormRef.value.validate()
        loading.value = true
        
        await authStore.login({
          email: loginForm.email,
          password: loginForm.password,
          remember: loginForm.remember
        })
        
        ElMessage.success('Login successful!')
        router.push('/')
      } catch (error) {
        console.error('Login error:', error)
        ElMessage.error(error.message || 'Login failed. Please try again.')
      } finally {
        loading.value = false
      }
    }
    
    const setDemoCredentials = (type) => {
      if (type === 'admin') {
        loginForm.email = 'admin@datamesh.io'
        loginForm.password = 'admin123'
      } else {
        loginForm.email = 'user@datamesh.io'
        loginForm.password = 'user123'
      }
    }
    
    return {
      loginFormRef,
      loginForm,
      loginRules,
      loading,
      isDev,
      handleLogin,
      setDemoCredentials,
      Message,
      Lock
    }
  }
}
</script>

<style scoped>
.login-form {
  width: 100%;
}

.login-form h2 {
  margin: 0 0 8px 0;
  font-size: 24px;
  font-weight: 600;
  color: var(--el-text-color-primary);
  text-align: center;
}

.login-form p {
  margin: 0 0 32px 0;
  color: var(--el-text-color-secondary);
  text-align: center;
}

.login-options {
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 100%;
}

.forgot-link {
  color: var(--el-color-primary);
  text-decoration: none;
  font-size: 14px;
}

.forgot-link:hover {
  color: var(--el-color-primary-light-3);
}

.login-button {
  width: 100%;
  height: 48px;
  font-size: 16px;
  font-weight: 500;
}

.login-footer {
  text-align: center;
  margin-top: 24px;
}

.login-footer p {
  margin: 0;
  color: var(--el-text-color-secondary);
  font-size: 14px;
}

.login-footer a {
  color: var(--el-color-primary);
  text-decoration: none;
  font-weight: 500;
}

.login-footer a:hover {
  color: var(--el-color-primary-light-3);
}

.demo-credentials {
  margin-top: 24px;
  padding: 16px;
  background: var(--el-fill-color-light);
  border-radius: 8px;
}

.demo-buttons {
  display: flex;
  gap: 8px;
  justify-content: center;
}

/* Focus styles */
.el-input:focus-within {
  box-shadow: 0 0 0 2px var(--el-color-primary-light-8);
}

/* Mobile responsive */
@media (max-width: 768px) {
  .login-form h2 {
    font-size: 20px;
  }
  
  .login-options {
    flex-direction: column;
    gap: 8px;
    align-items: flex-start;
  }
  
  .demo-buttons {
    flex-direction: column;
  }
}
</style>
